git:
  depth: 2
language: node_js
branches:
  except: /^v\d/
node_js:
  - iojs
  - node
# https://github.com/hvr/multi-ghc-travis
env:
  - CABALVER=1.22 GHCVER=7.10.2
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal update
  - cabal install --constraint=transformers\ installed happy alex
script:
  - npm run-script pretest
  - npm run-script coverage
after_script:
  - npm install istanbul-coveralls
  - node node_modules/.bin/istanbul-coveralls
notifications:
  email: false
